site_name: Zen Sets 1.3.4 for Blender
site_description: Zen Sets 1.3.4 for Blender Documentation
nav:
    - Introduction: index.md
    - Installation: installation.md
    - N-Panel: npanel.md
    - View3D Tool: workspacetool.md
    - Import-Export: imp_exp.md
    - Tools: tools.md
    - Preferences: preferences.md
    - Help: help.md
    - Downloads: downloads.md
    - Troubleshooting: troubleshooting.md
    - Changelog: changelog.md
    - API: api.md

docs_dir: mkdocs
site_dir: docs
theme: readthedocs

markdown_extensions:
    - smarty
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: 