site_name: Zen Sets for Blender
site_description: Zen Sets for Blender Documentation
nav:
    - Introduction: index.md
    - Installation: installation.md
    - N-Panel: npanel.md
    # - Pie Menu: pie-menu.md
    # - Advanced UV Maps: adv_uv-maps.md
    # - Seam Groups: seam_groups.md
    # - Operators: operators.md
    # - Unwrap: unwrap.md
    # - Select: select.md
    # - Pack: pack.md
    # - Checker Map: checker.md
    # - Controls: controls.md
    # - Texel Density: texel_density.md
    # - Transform: transform.md
    # - Stack: stack.md
    - Preferences: preferences.md
    - Help: help.md
    - Downloads: downloads.md
    - Troubleshooting: troubleshooting.md
    - Changelog: changelog.md
docs_dir: mkdocs
site_dir: docs
theme: readthedocs
markdown_extensions:
    - smarty
    - admonition